### ISSUE TITLE
23 - Créer une nouvelle disponibilité, English ou French?

### ISSUE THREAD

**Issue by jfillion12394** [WildCodeSchool/orleans-202103-php-project-coachmoi#316]
1)  Le bouton "SAVE" est en anglais ??? Si on parle pas anglais, comment on fait?

2) dans les heures de debut et fin on doit mettre à la fin PM et AM ?? Si on parle pas anglais, comment on fait?

**Comment by Serdar45000** [comment]
Les horaires s'affichent en fonction de la langue de ton OS ! sur ma version  FR de ubuntu je n'ai pas le AM & PM mais bien 00h00->24h ! & sur ma version anglaise de ubuntu  j'ai également AM & PM
