### ISSUE TITLE
99 SUPERADMIN/RESA

### ISSUE THREAD

**Issue by eguesbaya** [WildCodeSchool/orleans-202103-php-project-coachmoi#446]
la mise en relation salle/coach/client se fait sur les activités c'est bien ça ? pas de prise en compte auto des disponibilités mais juste là à titre informatif ?

**Comment by Thuydieutran** [comment]
> la mise en relation salle/coach/client se fait sur les activités c'est bien ça ? pas de prise en compte auto des disponibilités mais juste là à titre informatif ?

C'est le superadmin qui regarde les dispo des coachs + salles pour les matcher
